# Generated by Django 5.2 on 2025-04-06 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazki', to='reviews.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('ocena', models.PositiveSmallIntegerField()),
                ('autor_recenzji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzje', to='reviews.ksiazka')),
            ],
            options={
                'unique_together': {('ksiazka', 'autor_recenzji')},
            },
        ),
    ]
