# Generated by Django 5.2 on 2025-04-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='okladka',
            field=models.ImageField(blank=True, null=True, upload_to='okladki/'),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='nazwa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.kategoria'),
        ),
    ]
