# Generated by Django 5.2 on 2025-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_ksiazka_okladka_alter_kategoria_nazwa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='info_autora',
            field=models.TextField(blank=True, default=''),
        ),
    ]
